name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - ydata-profiling=4.5.1
  - pyarrow=2.0
  - pip:
      - wandb==0.10.31